pygments:       true
permalink:      /:categories/:title/
paginate:       5

exclude:
    - README.md
    - Rakefile

title:          whentp
url:            http://appden.com
feed:           /atom.xml
description:    "whentp@github"
comment:        I don't know.

author:
    name:       whentp
    email:      tpsmsproject@gmail.com
    twitter:    whentp
    
about: >
    I'm whentp.
    
disqus:
    id:         whentp

nav:
    - name:     Blog
      url:      /
    
    - name:     About
      url:      /about/
      subnav:
        - name: Contact
          url:  mailto:tpsmsprojectatgmaildotcom
    

footer:
    - verb:     Thinking
      action:   I have no idea.
      
copyright:
    - "&copy; Copyright 2010, whentp. All Rights Reserved."
      
css:
    - /lib/style.css
    - /lib/syntax.css
    
js:
    - http://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools-yui-compressed.js
    - /lib/mootools-more.js
    - /lib/appden.js
